
<section class="container-fluid">

    <h2>Notre Restaurant</h2>
        <div class="row">
            <div class="imgHome col-md-5">
            <img class="img-fluid  mx-md-3" src="../www/image/restoAccueil1.jpg" alt="resto" class="img-fluid">
            </div>
     <article class="col-md-6 mx-md-3 mb-4">
    <p>Willy Dumont, chef de cuisine confirmé, a le plaisir de vous accueillir dans son nouveau restaurant « Le Diamant de Paris ».</p>

    <p> Avec son équipe, il vous propose une cuisine exclusivement faite maison, préparée à partir de produits frais et uniquement de saison .</p>

    <p>Savoureuse et gourmande, notre cuisine ravira toutes les demandes : végétariens, amateurs de viandes ou de poissons … vous êtes tous les biens venus !</p>

    Petit Resto , c’est aussi la possibilité d’organiser des évènements en privatisant la salle du bas.</p>
         <button class="btn btn-info mt-2">Reserver une table</button>
         <button class="btn btn-danger mt-2">Livraison à domicile</button>
     </article>
        </div>

</section>
