<aside  class="card col-md-3">
<div class="card-body">
    <h4 class="card-title"> infos pratique</h4>
    <p>150 rue Jean Jaures</p>
    <p>75012 PARIS</p>
</div>
    <div class="card-body">
    <h5 class="card-title">Métro</h5>
<p>RER ligne c ,Métro ligne place d'italie</p>
    </div>
        <div class="card-body">
    <h5 class="card-title">Bus</h5>
    <p>Bus 250,31</p>
        </div>
            <div class="card-body">
    <h5 class="card-title">Horaire</h5>
    <p>Lundi - Dimanche</p>
    <p>11h00 - 14h00</p>
    <p>18h00 - 23h00</p>
            </div>
                <div class="card-body">
    <h5 class="card-title">Service</h5>
    <p>Terrasse</p>
   </div>
</aside>