<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Au petit resto <?php if(isset($title)) { echo " - ".$title; } ?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" href="<?= $router->getWwwPath() ?>/css/style.css" >

</head>
<header>

    <ul class="nav  flex-column flex-sm-row mb-md-5 ">
        <li class="nav-item dropdown">
            <a class="nav-link  " data-toggle="dropdown" href="">Mon compte
            <div class="dropdown-menu">
                <a class="dropdown-item" href="<?=$router->generatePath("resto_user_inscription") ?>">se connecter</a>
                <a class="dropdown-item" href="<?=$router->generatePath("resto_user_profil") ?>">mon profil</a>
            </div>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link  " href="<?=$router->generatePath("resto_booking") ?>">Reservation</a>

        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?=$router->generatePath("resto_plat_showAll") ?>">La carte</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?=$router->generatePath("resto_menu") ?>">Menu</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="<?=$router->generatePath("resto_reviews") ?>" >Avis</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="<?=$router->generatePath("resto_contact") ?>" >Nous contactez</a>
        </li>

    </ul>


    <h1 class="py-5 py-md-5">Au petit Resto</h1>
    <div class="container-fluid">
        <div class="row  justify-content-between">
<a class=""><p>Votre panier<i class=" fas fa-shopping-cart"></i></p></a>
            <?php if($userSession->isAuthenticated()): ?>
                <p>bienvenue <?= $userSession->getFirstName(); ?></p>
                <a href="<?= $router->generatePath("resto_user_logout") ?>" class="m-2">se deconnectez</a>
            <?php else: ?>
                <a href="<?=$router->generatePath("resto_user_login") ?>"  class="m-2" >se connectez</a>
            <?php endif ?>
        </div>
    </div>
</header>
<body>
    <?php foreach ($flashBag->getAllMessages() as $message): ?>
        <p class="flashbag" ><?= $message; ?></p>
    <?php endforeach ?>
    <main>

        <?php include $templatePath ?>


    </main>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="<?= $router->getWwwPath() ?>/js/moment.js"> </script>


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="<?= $router->getWwwPath() ?>/js/index.js"></script>
<script src="<?= $router->getWwwPath() ?>/js/validationForm.js"></script>
</body>
</html>


