<h2>Commander ce menu</h2>
<form method="POST" class="form-group">
    <h3>Ma commande</h3>

    <table class="table row ">
        <tr>
            <td>menu</td>
            <td>quantité</td>
        </tr>

    <?php foreach ($orders as $order): ?>
    <tr>

        <td><?= $order['title'] ?></td>
        <td><form method="post" action="<?=$router->generatePath("resto_Order_create")?>">
                <label>quantity</label>
                <input type="number" name="quantity" id="quantity" placeholder="">

            </td>
    </tr>
    <?php endforeach ?>
        <input type="submit" value="valider" hidden="hidden">
    </table>

    <div>
        <label>Quand voulez-vous etre livré ?</label>
       <input type="date" name="delivery" id="delivery" class="form-control">
    </div>
    <div class="form-group">
        <label for="payed">Payment</label>
        <select id="payed" name="payed" class="form-control">
            <option value="0"> à la livraison</option>
            <option value="1">par carte bleue</option>

        </select>
    </div>
    <input type="submit" value="commander"  class="btn btn-info">

</form>