<h2>Votre panier</h2>
<div class="container">
<?php if(empty($allOrderLines)): ?>
    <h4>Votre Panier est vide pour l'instant</h4>
    <p style="color: red">Dépéchez vous de consommer!!!</p>
<?php else: ?>
<table class="table row">
    <tr>
        <th>Menu</th>

        <th>Quantité</th>
        <th>Prix Unitaire</th>
        <th>Prix Total</th>

        <th>Modifier / Supprimer</th>
    </tr>

   <?php $total= 0; ?><!-- création variable du grand total de la commande-->
        <?php foreach ($allOrderLines as $orderLine): ?>
            <?=htmlspecialchars($orderLine['order_id']) ?>
            <tr class="removableContainer" id="line<?=htmlspecialchars($orderLine["orderDetails_id"])?>">
                <td >
                    <?=htmlspecialchars($orderLine["title"]) ?>
                </td>

                <td class="quantityOrdered">
                    <?=htmlspecialchars($orderLine['QuantityOrdered']) ?>
                </td>
                <td>
                    <span class="priceEach"><?= number_format(htmlspecialchars($orderLine['priceEach']), 2)?></span>&nbsp;€
                </td>
                <td>
                    <span class="subTotalPrice"><?= number_format(htmlspecialchars($orderLine['QuantityOrdered']) *htmlspecialchars($orderLine['priceEach']), 2)?></span>&nbsp;€
                    <?php $total +=htmlspecialchars($orderLine['QuantityOrdered']) * htmlspecialchars($orderLine['priceEach']) ?><!-- incrémentation du grand total de la commande-->
                </td>
                    <td class="edit-suppr">
                        <select class="update-basket-line" data-action="<?= $router->generatePath("resto_order_updateItemQuantity")?>" data-id="<?=htmlspecialchars($orderLine["orderDetails_id"])?>">
							<?php for($i=0; $i<=$orderLine['QuantityOrdered']+5; $i++): ?>
                                <option value="<?= $i ?>" <?php if($i== $orderLine['QuantityOrdered']):?>selected="selected"<?php endif; ?>><?= $i ?></option>
							<?php endfor; ?>
                        </select>
                        <button>
                            <a href="#" id="orderlinTrash<?=htmlspecialchars($orderLine["orderDetails_id"])?>" class="delete-basket-item" data-action="<?= $router->generatePath("resto_order_removeItem")?>" data-id="<?=htmlspecialchars($orderLine["orderDetails_id"])?>">
                                <i class="fas fa-trash-alt"></i>Enlever du panier
                            </a>
                        </button>
                    </td>

            </tr>

        <?php endforeach; ?>
    </table>
    <p>TOTAL : <span id="totalPrice"><?= $total ?></span>&nbsp;€</p>

    <form action="<?=$router->generatePath("resto_order_confirmBasket")?>" method="post" >
        <div class="group-form">
        <label for="DeliveryDate">Date de livraison</label>
        <input type="date" name="DeliveryDate" id="DeliveryDate" class="form-control" >


        <input type="submit" value="confirmer" class="form-control btn btn-info" >
        </div>
    </form>


<button>
    <a href="<?= $router->generatePath('resto_order_emptyBasket') ?>">
        <i class="fas fa-trash-alt"></i>Vider le panier
    </a>
</button>
<?php endif; ?>
</div>
<script src="<?= $router->getWwwPath() ?>/js/index.js"></script>
<script src="<?= $router->getWwwPath() ?>/js/validationForm.js"></script>
