<h1><?= $title ?></h1>

<form  method="POST" enctype="multipart/form-data">
    <div class="container-fluid col-sm-10 formRequired"> </div>
    <div class="form-group">
    <label for="namePlat">Le nom du plat</label>
    <input type="text" id="namePlat" name="product" class="form-control inputRequired">
    </div>
    <div class="form-group">
        <label>description du plat</label>
    <textarea rows="3" cols="50" id="product_description" name="product_description" class="form-control inputRequired"></textarea>
    </div>
    <div class="form-group">
    <label for="ingredient">Les ingredients</label>
    <textarea rows="3" cols="50" id="ingredient" name="ingredient" class="form-control inputRequired"></textarea>
    </div>
    <div class="form-group">
    <label for="price">le prix</label>
    <input type="text" id="price" name="price" class="form-control inputRequired">
    </div>
    <div class="form-group">
    <label for="photo">Url de la photo</label>
    <input type="file" id="photo" name="photo" class="form-control">
    </div>
        <div class="form-group">
    <label for="category">Choix de la categorie</label>
    <select id="category" name="category" class="form-control">
        <option value="entrée">entrée</option>
        <option value="plat principal">plat principal</option>
        <option value="dessert">dessert</option>


    </select>
    </div>
    <input type="submit" value="sauver"  class="btn btn-info">
</form>
<script src="<?= $router->getWwwPath() ?>/js/validationForm.js"></script>