<?php ( var_dump($allMenu)) ?>
<section class="container-fluid col-sm-10">
    <div class="row">
        <div class=" col-md-9">
            <h2><?=$plat['product']?></h2>
            <article class="row ">
                 <img class="img-thumbnail col-sm-5" src="<?= $router->getWwwPath() ?>/upload/photosPlats/<?=$plat['photo'] ?>" class="px-5 col-sm-5">
                <div class="caption col-sm-5">
                    <p class="m-3"><?=$plat['product_description'] ?></p>
                     <p class="btn btn-info">Prix : <?=$plat['price'] ?> € </p>
                </div>
                    <p class="mt-3">Ce plat est composé de : <?=$plat['ingredient'] ?></p>
                <?php if($allMenu): ?>
                <?php foreach ($allMenu as $Menu) : ?>
                    <p>Disponible à la livraison dans le <?= htmlspecialchars($Menu['title'])?> </p>
                <?php endforeach; ?>
                <a href="<?=$router->generatePath("resto_menu") ?>"> commander</a>
                <?php endif; ?>

            </article>
               <div class="card col-md-8 d-flex align-items-center">
                   <div class="card-body">
                       <h5 class="card-title">Réservation</h5>
                       <p class="card-body btn btn-info ">Réserver une table</p>
                   </div>
               </div>

            <a class="btn btn-info" href="<?=$router->generatePath("resto_plat_showAll") ?>">Retour </a>

        </div>

         <?php include $this->viewPath."asideView.phtml"; ?>
    </div>
</section>
