<main class="container" >

    <h2><?= $title ?></h2>

    <h3 class="mb-4"><?=htmlspecialchars($menu['title']) ?></h3>
    <div class="row ">



        <?php foreach ($plats as $plat): ?>

            <div class=" col-sm-8 col-lg-4 d-flex justify-content-center " >

                <article class=" card col-md-12">
                    <p><?=htmlspecialchars($plat["category"]) ?></p>
                    <p class="card-tirle"><?=htmlspecialchars($plat["product"]) ?></p>
                    <p class="card-body "><?=htmlspecialchars($plat["ingredient"]) ?></p>

                    <?php if($plat['photo']): ?>
                        <img class="mb-5" src="<?= $router->getWwwPath() ?>/upload/photosPlats/<?=$plat['photo'] ?>" >
                    <?php else: ?>
                        <img src="<?= $router->getWwwPath() ?>/image/default-plat.jpg" >
                    <?php endif ?>

                </article>

            </div>
            <?php endforeach; ?>
         <p class=""><?= htmlspecialchars($menu['content']) ?></p>

        <div class=" ">

        <p class=" m-5 btn  btn-info">Au prix de : <?=htmlspecialchars($menu['price_menu']) ?> €</p>
         <p class="mb-5">valable du <?= (new DateTime(htmlspecialchars($menu["startDate"])))->format("d/m/Y"); ?> au <?= (new DateTime($menu["endDate"]))->format("d/m/Y"); ?></p>

            <a class="btn btn-info" href="<?=$router->generatePath("resto_menu") ?>">Retour</a>

            <section>
                <h4>Ce que les clients en pensent :</h4>
                <?php foreach ($allReviews as $reviews) : ?>
                <?= $reviews['comment'] ?>
                    <div class="stars">
                        <p>Note du menu :<?=htmlspecialchars($reviews['note'])?>
                            <?php for($i=0;$i<htmlspecialchars($reviews['note']);$i++){ ?>
                                <i class="fa fa-star gold"></i>
                            <?php }?>
                        </p>
                    </div>
                <?=htmlspecialchars($reviews['FirstName']) ?> le <?=(new DateTime(htmlspecialchars($reviews["dateCreation"])))->format("d/m/Y");?>
                <?php endforeach; ?>
            </section>
            <a class="btn btn-info mb-3" href="<?=$router->generatePath("resto_Menu") ?>"> Retour</a>

</main>