

<h2><?= $title ?></h2>
<?php if($userSession->isAdmin()): ?>
<a href="<?=$router->generatePath("resto_menu_create") ?>">Crée un menu</a>
<?php endif; ?>
<section class="menu container">
    <div class="row">

            <table class="table row">
                <tr>
                <td>menu</td>
                <td>plat</td>
                <td>supplement</td>
                <td>prix</td>
                </tr>
                <?php foreach ($allMenus as $menu) :?>
                <tr>
                    <td><?=htmlspecialchars($menu["title"] )?></td>

                    <td>
                    <?php foreach ($allPlats[$menu['menu_id']] as $plat) : ?>

                        <P> <?=htmlspecialchars($plat['product'] ) ?></P>

                    <?php endforeach; ?>
                    </td>
                    <td><?=nl2br(htmlspecialchars($menu["content"])) ?></td>
                    <td><?=htmlspecialchars($menu["price_menu"]) ?> €</td>
                    <td><a href="<?=$router->generatePath("resto_menu_showOne") ?>?id=<?=$menu['menu_id'] ?>"> <i class="fas fa-plus-circle"></i> Voir ce menu</a></td>
                    <td><?php if($userSession->isAdmin()): ?>

                            <button id="removeInput-<?=htmlspecialchars($menu["menu_id"])?>" class="remove-button" data-action="<?= $router->generatePath("resto_menu_remove")?>" data-id = "<?= $menu["menu_id"]?>">Supprimer</button>
                                <a href="<?=$router->generatePath("resto_menu_update") ?>?id=<?=htmlspecialchars($menu['menu_id']) ?>">Modifier le menu</a>



                        <?php else: ?>
                    <td class="order-block">
                        <p>Quantité</p>
                        <select class="quantity">
                            <?php for($i=1; $i<=10; $i++): ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                            <?php endfor; ?>
                        </select>
                        <button>
                            <a href="#" id="cartInput-<?=htmlspecialchars($menu["menu_id"])?>" class="add-to-basket" data-action="<?= $router->generatePath("resto_order_add")?>" data-id="<?=htmlspecialchars($menu["menu_id"])?>">
                                <i class="fas fa-shopping-cart"></i>Ajouter au panier
                            </a>

                        </button>

                    </td>
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            </table>

        </div>

<!--        --><?php //include $this->viewPath."asideView.phtml"; ?>


</section>

<script src="<?= $router->getWwwPath() ?>/js/index.js"></script>
<script src="<?= $router->getWwwPath() ?>/js/validationForm.js"></script>

