<main class="container-fluid">

    <h2><?= $title ?></h2>
<?= var_dump($allReviews)?>
    <h3 class="mb-4"><?=htmlspecialchars($menu['title']) ?></h3>
    <div class="row m-auto">
        <p class="col-md-2 ml-3"><?= htmlspecialchars($menu['content']) ?></p>


     <div class=" col-md-5" >
            <?php foreach ($plats as $plat): ?>
                <?php if($plat["category"]=='entrée'): ?>
                    <p>Entrée :</p>
                    <p class=" "><?=htmlspecialchars($plat["product"]) ?></p>
                    <?php if($plat['photo']): ?>
                        <img class="mb-5" src="<?= $router->getWwwPath() ?>/upload/photosPlats/<?=$plat['photo'] ?>" >
                    <?php else: ?>
                        <img src="<?= $router->getWwwPath() ?>/image/default-plat.jpg" >
                    <?php endif ?>
                <?php endif; ?>
            <?php if($plat["category"]=="plat principal"): ?>
            <p>Plat principal :</p>
            <p class=" "><?=htmlspecialchars($plat["product"]) ?></p>
                <?php if($plat['photo']): ?>
                    <img class="mb-5" src="<?= $router->getWwwPath() ?>/upload/photosPlats/<?=$plat['photo'] ?>" >
                <?php else: ?>
                    <img src="<?= $router->getWwwPath() ?>/image/default-plat.jpg" >
                <?php endif ?>
            <?php endif; ?>
                <?php if($plat["category"]=="dessert"): ?>
                    <p>Dessert :</p>
                    <p class="mb-3 "><?=htmlspecialchars($plat["product"]) ?></p>
                    <?php if($plat['photo']): ?>
                        <img class="mb-5" src="<?= $router->getWwwPath() ?>/upload/photosPlats/<?=$plat['photo'] ?>" >
                    <?php else: ?>
                        <img class="mb-5" src="<?= $router->getWwwPath() ?>/image/default-plat.jpg" >
                    <?php endif ?>
                <?php endif; ?>

            <?php endforeach; ?>
      </div>
        <div class="col-md-4 ">
        <p>Au prix de :</p>
        <p class=" mb-5"><?=$menu['price_menu'] ?> €</p>
         <p class="mb-5">valable du <?= (new DateTime($menu["startDate"]))->format("d/m/Y"); ?> au <?= (new DateTime($menu["endDate"]))->format("d/m/Y"); ?></p>
    <a href="<?=$router->generatePath("resto_Order_add")?>?id=<?=$menu['menu_id'] ?>" class="btn btn-info mb-5">Ajouter au panier</a>
            <a class="btn btn-info" href="<?=$router->generatePath("resto_menu") ?>">Retour</a>

            <section>
                <h4>Ce que les clients en pensent :</h4>
                <?php foreach ($allReviews as $reviews) : ?>
                <?= $reviews['comment'] ?>
                    <div class="stars">
                        <p>Note du menu :<?= $reviews['note']?>
                            <?php for($i=0;$i<$reviews['note'];$i++){ ?>
                                <i class="fa fa-star gold"></i>
                            <?php }?>
                        </p>
                    </div>
                <?= $reviews['FirstName'] ?> le <?=(new DateTime($reviews["dateCreation"]))->format("d/m/Y");?>
                <?php endforeach; ?>
            </section>

</main>