<h3>Creer votre compte</h3>

<form method="POST" class="container-fluid col-sm-10">
    <div class="form-row ">
    <div class="form-group col-md-6">
    <label for="firstName">Votre prénom</label>
    <input class="form-control inputRequired" type="text" id="firstName" name="FirstName"  >
    </div>
    <div class="form-group col-md-6">
        <label for="lastName">Votre nom</label>
        <input class="form-control inputRequired" type="text" id="lastName" name="LastName"  >
    </div>
    </div>
    <div class="form-group">
        <label for="email">E-mail</label>
        <input class="form-control inputRequired" type="email" id="email" name="email"  >
    </div>
    <div class="form-row">
    <div class="form-group col-md-4">
        <label for="address">adresse</label>
        <input class="form-control inputRequired" type="text" id="address" name="address"  >
    </div>
    <div class="form-group col-md-4">
        <label for="codePostal">code postal</label>
        <input class="form-control inputRequired" type="text" id="codePostal" name="postCode"  >
    </div>
    <div class="form-group col-md-4">
        <label for="city">ville</label>
        <input class="form-control inputRequired" type="text" id="city" name="city"  >
    </div>
    </div>
    <div class="form-row">
    <div class="form-group col-md-6">
        <label for="login">Password</label>
        <input class="form-control inputRequired" type="password" id="password" name="password"  >
    </div>
    <div class="form-group col-md-6">
        <label for="phone">Téléphone</label>
        <input class="form-control inputRequired" type="text" id="phone" name="phone"  >
    </div>
    </div>
        <input class="btn btn-info mx-5 " type="submit" value="sauver">

</form>