<h2>Laisser un commentaire sur le <?= $menu['title'] ?></h2>


<form method="post" >
    <div class="form-group">
    <label for="comment">Commentaire</label>
    <textarea name="comment" id="comment" class="form-control"></textarea>
    </div>
    <div>
        <label for="name">votre note</label>
        <input type="text" name="note" id="name" class="form-control">
    </div>

    <input type="submit" value="envoyer">
</form>