<H2>Vos avis</H2>


<?php foreach ($allReviews as $review) : ?>
<p><?=htmlspecialchars($review['comment'] )?></p>
<p><?=htmlspecialchars($review['FirstName'])?> <?=htmlspecialchars($review['LastName'])?> sur le <?=htmlspecialchars($review['title']) ?> le <?=(new DateTime(htmlspecialchars($review["dateCreation"])))->format("d/m/Y");?></p>
    <div class="stars">
        <p>Note du menu :
        <?php for($i=0;$i<$review['note'];$i++){ ?>
        <i class="fa fa-star gold"></i>
        <?php }?>
        </p>
    </div>
<?php endforeach;?>